### ISSUE TITLE
Bungeecord support

### ISSUE THREAD

**Issue by theoparis** [WeLikeToCodeStuff/Minecraft-Server-Creator#1]
add bungeecord support pls

Also maybe a bit overkill but it would be nice to see a complete server/mc network **manager** with a cli tool for it that goes along with this generator. Eg. Manage and start/stop all servers from a single cli tool

**Comment by DeveloperNeon** [comment]
Am finishing adding bungee support. Also managing start and stop all servers and everything would probably be done with a ui.

**Comment by DeveloperNeon** [comment]
Bungeecord support added, Working on the web panel.
